<?php declare(strict_types=1);$activeNav='';$pageTitle='Impressum';$pageDescription='Anbieterangaben, Hinweise zu Inhalten und Datenschutz bei Thailand Insight.';require __DIR__.'/includes/page-start.php';?>
<style>
.legal-layout{max-width:1100px;margin:0 auto}.legal-layout h2{font:600 clamp(38px,4vw,56px)/1.05 var(--serif);margin:0 0 27px;color:#102d31}.legal-layout h3{font:600 clamp(27px,3vw,36px)/1.1 var(--serif);margin:0 0 14px;color:#102d31}.legal-layout p{font-size:16px;line-height:1.8;color:#384a48;margin:0 0 18px}.legal-layout .legal-eyebrow{font:700 11px/1.4 var(--sans);letter-spacing:.25em;text-transform:uppercase;color:#9a7535;margin:0 0 15px}.legal-panel{padding:clamp(24px,4vw,46px);background:#fffaf1;border:1px solid #e9dfd0;box-shadow:0 14px 35px rgba(16,45,49,.055);margin-bottom:28px}.legal-panel--accent{border-left:4px solid #c59a49}.legal-panel .legal-detail{display:grid;grid-template-columns:minmax(150px,220px) minmax(0,1fr);gap:14px 30px;margin:0}.legal-detail dt{font-weight:700;color:#233a39}.legal-detail dd{margin:0;color:#384a48;line-height:1.7;overflow-wrap:anywhere}.legal-placeholder{letter-spacing:.1em;color:#8d8375}.legal-divider{border:0;border-top:1px solid #e7ddce;margin:30px 0}.legal-layout a{overflow-wrap:anywhere}.legal-layout .legal-privacy{margin-top:70px}.legal-layout .legal-note{font-size:14px;color:#5c6864}.legal-copy p:last-child{margin-bottom:0}
@media(max-width:650px){.legal-panel .legal-detail{grid-template-columns:1fr;gap:3px}.legal-detail dd{margin-bottom:16px}.legal-detail dd:last-child{margin-bottom:0}}
</style>
<section class="page-hero" style="min-height:460px"><img src="assets/img/hero-poster.jpg" alt="Thailand Insight"><div class="page-hero-copy"><p class="eyebrow">Rechtliches</p><h1>Impressum</h1><p>Angaben zum Anbieter und Hinweise zu dieser Webseite.</p></div></section>
<section class="section section--paper"><div class="legal-layout">
  <h2>Anbieterkennzeichnung</h2>
  <section class="legal-panel legal-panel--accent" aria-labelledby="legal-provider"><p class="legal-eyebrow">Thailand Insight</p><h3 id="legal-provider">Anbieterin dieser Webseite</h3><p class="legal-placeholder">…………………………………………..<br>……………………………………….<br>………………………………………..</p><hr class="legal-divider"><dl class="legal-detail"><dt>Kontakt</dt><dd>E-Mail: <a class="text-link" href="mailto:info@thailand-insight.com">info@thailand-insight.com</a></dd><dt>Registrierung</dt><dd>Handelsregisternummer: <span class="legal-placeholder">………………………………</span></dd></dl></section>
  <section class="legal-panel" aria-labelledby="legal-content"><h3 id="legal-content">Kontakt für die Inhalte dieser Webseite</h3><p class="legal-placeholder">…………………………….<br>………………………….</p><p>…………………………. betreibt diese Webseite. Die digitale Reisebegleiterin „Sandra“ wird ebenfalls von ………………………………….. Ltd. angeboten. …………………………. hat Sandra konzipiert und entwickelt.</p></section>

  <section class="legal-panel legal-copy" aria-labelledby="legal-sandra"><p class="legal-eyebrow">Hinweise</p><h3 id="legal-sandra">Hinweise zu Inhalten und zu Sandra – Disclaimer</h3>
    <p>Die Inhalte von Thailand Insight Group dienen der allgemeinen Information über Reisen und Aufenthalt in Thailand. Wir erstellen sie mit Sorgfalt. Dennoch können sich insbesondere Öffnungszeiten, Preise, Verfügbarkeit, Verkehrsverbindungen, Einreisebestimmungen und andere örtliche Gegebenheiten kurzfristig ändern. Prüfen Sie Angaben, die für Ihre Entscheidung wichtig sind, zusätzlich bei den zuständigen Stellen oder beim jeweiligen Anbieter.</p>
    <p><strong>Sandra</strong> ist eine digitale, teilweise KI-gestützte Begleiterin für Pattaya und die direkte Umgebung. Sie unterstützt bei allgemeinen Fragen, der Suche nach Orten und Angeboten sowie bei Übersetzungen zwischen Deutsch und Thai. Automatisch erzeugte Antworten können unvollständig oder fehlerhaft sein. Sandra gibt keine verbindlichen Zusagen über Angebote Dritter.</p>
    <p>Angaben zu Orten, Adressen, Öffnungszeiten, Preisen und Leistungen können sich ändern. Bitte prüfen Sie wichtige Angaben unmittelbar beim jeweiligen Anbieter, beispielsweise telefonisch. Automatische Übersetzungen können Bedeutung, Zusammenhang oder Höflichkeit verändern. Lassen Sie wichtige Aussagen von einer sprachkundigen Person überprüfen.</p>
    <p>Sandra bietet keine medizinische, rechtliche oder finanzielle Beratung. Sie ersetzt insbesondere keine fachliche Beurteilung gesundheitlicher Beschwerden und keine professionelle Übersetzung für rechtlich oder wirtschaftlich bedeutsame Vereinbarungen.</p>
    <p>Diese Webseite kann Links zu Angeboten Dritter enthalten. Beim Aufrufen gelten deren Inhalte und Datenschutzinformationen. Wir machen uns fremde Inhalte durch die bloße Verlinkung nicht zu eigen.</p>
    <p>Eine jederzeit ununterbrochene oder fehlerfreie Verfügbarkeit der Webseite oder von Sandra kann nicht zugesagt werden. <strong>Zwingende gesetzliche Rechte und gesetzlich nicht ausschließbare Haftungsansprüche bleiben unberührt.</strong></p>
  </section>

  <section class="legal-privacy" id="datenschutz" aria-labelledby="legal-privacy-heading"><p class="legal-eyebrow">Datenschutz</p><h2 id="legal-privacy-heading">Datenschutz – Text für die Webseite, noch zu vervollständigen</h2>
    <div class="legal-panel legal-panel--accent"><h3>Verantwortliche Stelle</h3><p class="legal-placeholder">……………………………………….<br>……………………………….<br>……………………………………….<br>……………………………………………</p><p>E-Mail: <a class="text-link" href="mailto:info@thailand-insight.com">info@thailand-insight.com</a></p></div>
    <div class="legal-panel legal-copy">
      <p>Beim Besuch dieser Webseite verarbeitet der Webserver technisch erforderliche Verbindungsdaten. Dazu können insbesondere IP-Adresse, Zeitpunkt des Zugriffs, aufgerufene Seite und Browserinformationen gehören. Diese Verarbeitung dient der Bereitstellung, Sicherheit und Fehlerbehebung der Webseite. Einzelheiten zum Hosting und zur Speicherdauer der Serverprotokolle müssen anhand des tatsächlich eingesetzten Hosters ergänzt werden.</p>
      <p>Wenn Sie uns über das Kontaktformular oder per E-Mail schreiben, verarbeiten wir Ihre übermittelten Kontaktdaten und Ihre Nachricht, um Ihre Anfrage zu beantworten und gegebenenfalls eine Zusammenarbeit vorzubereiten. Eine erforderliche weitere Aufbewahrung, etwa aufgrund gesetzlicher Pflichten, bleibt vorbehalten.</p>
      <p>Die Webseite lädt derzeit Schriftdateien von <strong>Google Fonts</strong>. Dabei können beim Aufruf Verbindungsdaten an Google übertragen werden. Ob und auf welcher Grundlage dies im konkreten Betrieb erfolgt, muss für die endgültige Datenschutzerklärung geprüft werden. Alternativ können die Schriftdateien lokal bereitgestellt werden.</p>
      <p>Die derzeitige Sandra-Seite auf thailandinsightgroup.com stellt Sandra vor. <strong>Der bloße Besuch dieser Informationsseite ist nicht gleichbedeutend mit der Nutzung des Chats oder des Mikrofons in der App.</strong> Für die spätere Nutzung der Sandra-App müssen Chat, Sprachverarbeitung, beteiligte Dienstleister, Speicherdauer und Abonnements in einer eigenen, auf den tatsächlichen Betrieb abgestimmten Datenschutzinformation erläutert werden.</p>
      <p>Betroffene Personen können nach Maßgabe des anwendbaren Datenschutzrechts insbesondere Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Widerspruch verlangen sowie sich bei einer zuständigen Datenschutzaufsichtsbehörde beschweren. Anfragen richten Sie an die oben genannte Kontaktadresse.</p>
    </div>
    <div class="legal-panel"><h3>Noch offen für eine veröffentlichungsreife Datenschutzerklärung</h3><p>Tatsächlicher Hoster, Speicherdauer, konkrete Rechtsgrundlagen und Empfänger, gegebenenfalls weitere Cookies, Analyse- oder Marketingdienste.</p><p class="legal-note">Der Satz „Eine Weitergabe an Dritte erfolgt nicht“ wird nicht übernommen: Schon Hosting und extern geladene Schriften können Datenübermittlungen mit sich bringen.</p></div>
  </section>
</div></section>
<?php require __DIR__.'/includes/page-end.php';?>
