<?php
declare(strict_types=1);
require_once __DIR__.'/includes/config.php';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/nav.php';
$activeNav='home';$pageTitle='Thailand beginnt dort, wo Reiseführer aufhören';$pageDescription='Thailand Insight verbindet echte Erfahrungen, Reiseideen, digitale Guides und persönliche Orientierung für Thailand.';
require __DIR__.'/includes/page-start.php';
?>
<section class="hero" aria-label="Thailand Insight">
<div class="hero-media"><video data-hero-video autoplay muted loop playsinline preload="metadata" poster="assets/img/hero-poster.jpg"><source src="assets/video/hero.mp4" type="video/mp4"></video></div>
<div class="hero-content"><p class="eyebrow">Mehr als ein Reiseziel</p><h1>Thailand beginnt dort,<br>wo Reiseführer aufhören.</h1><p class="hero-lead">Echte Einblicke. Persönliche Erfahrungen. Praktische Orientierung – für alle, die Thailand nicht nur besuchen, sondern wirklich verstehen wollen.</p><div class="button-row"><a class="button button--gold" href="ueber-thailand.php">Thailand entdecken <span>→</span></a><a class="button button--ghost" href="ebooks.php">Unsere E-Books <span>→</span></a></div></div>
<button class="sound-button" type="button" data-sound-toggle aria-label="Ton einschalten"></button><span class="scroll-cue">Weiter entdecken ↓</span>
</section>
<section class="story-split" data-reveal><div><p class="eyebrow">Erfahrung statt Theorie</p><h2>Mehr als 20 Jahre Thailand – gelebte Erfahrung.</h2><p>Thailand ist für uns kein flüchtiges Urlaubsmotiv. Es ist Teil unseres Lebens, unserer Familie und unserer Geschichte. Wir teilen, was im Alltag wirklich zählt: ehrlich, verständlich und aus erster Hand.</p><a class="text-link" href="ueber-uns.php">Unsere Geschichte <span>→</span></a></div><figure><img src="assets/img/ebook-hero-photo.jpg" alt="Sonnenaufgang an Thailands Küste" loading="lazy"></figure></section>
<section class="section section--ink" id="reiseziele"><div class="section-head" data-reveal><div><p class="eyebrow">Vielfältig. Faszinierend. Eigenständig.</p><h2>Thailand entdecken</h2></div><p>Von pulsierenden Metropolen über stille Berglandschaften bis zu tropischen Inseln: Finde die Region, die zu deiner Art zu reisen passt.</p></div><div class="destination-grid" data-reveal>
<a class="destination-card" href="bangkok.php"><img src="assets/img/hero-poster.jpg" alt="Bangkok und Chao Phraya bei Sonnenuntergang"><div><h3>Bangkok</h3><p>Metropole, Tempel und Leben am Fluss</p></div></a>
<a class="destination-card" href="norden.php"><img src="assets/img/north-premium.jpg" alt="Berglandschaft und Lanna-Tempel in Nordthailand" loading="lazy"><div><h3>Nordthailand</h3><p>Kultur, Berge und ein anderer Rhythmus</p></div></a>
<a class="destination-card" href="zentralthailand.php"><img src="assets/img/region-central.jpg" alt="Historische Tempelanlage in Zentralthailand" loading="lazy"><div><h3>Zentralthailand</h3><p>Königsstädte und Geschichte</p></div></a>
<a class="destination-card" href="sueden-inseln.php"><img src="assets/img/south-premium.jpg" alt="Longtailboot und Kalksteininseln in Südthailand" loading="lazy"><div><h3>Süden & Inseln</h3><p>Andamanensee und Golf von Thailand</p></div></a></div></section>
<nav class="feature-band" aria-label="Reiseinformationen"><a href="reisevorbereitungen.php"><span>01</span><b>Einreise</b><span>Pass, Visa und erste Schritte</span></a><a href="klima.php"><span>02</span><b>Klima</b><span>Die passende Reisezeit</span></a><a href="sicherheit.php"><span>03</span><b>Sicherheit</b><span>Unterwegs mit Überblick</span></a><a href="sprache.php"><span>04</span><b>Sprache</b><span>Worte, die Türen öffnen</span></a><a href="ueber-thailand.php"><span>05</span><b>Kultur</b><span>Respektvoll verstehen</span></a></nav>
<section class="section section--dark"><div class="book-showcase" data-reveal><div class="editorial-copy"><p class="eyebrow">Praxiswissen aus erster Hand</p><h2>Unsere E-Books</h2><p>Digitale Reiseführer für Ankommen, Alltag und Entdecken – klar geschrieben, persönlich eingeordnet und jederzeit griffbereit.</p><a class="button button--gold" href="ebooks.php">Zur Bibliothek <span>→</span></a></div><div class="covers"><img src="assets/img/cover-ankommen.jpg" alt="E-Book Ankommen in Thailand"><img src="assets/img/cover-dach.jpg" alt="E-Book DACH Thailand"><img src="assets/img/cover-farang.jpg" alt="E-Book Leben als Farang"></div></div></section>
<section class="product-split" data-reveal><div class="product-visual"><img src="assets/img/sandra-hero-premium.jpg" alt="Thailand – persönliche Orientierung vor Ort" loading="lazy"></div><div class="product-copy"><p class="eyebrow">Deine persönliche Thailand-Begleiterin</p><h2>Sandra</h2><p>Sandra hilft dir in Pattaya und Umgebung, wenn du keine zwanzig Treffer brauchst, sondern höchstens drei wirklich passende Vorschläge.</p><ul class="check-list"><li>Lokale Orientierung in sechs Pattaya-Regionen</li><li>Konkrete Hilfe für Alltag und Reise</li><li>Separater Audio-Dolmetscher Deutsch ↔ Thai</li><li>Verständlich, persönlich und ohne Technikstress</li></ul><a class="button button--gold" href="sandra-app.php">Sandra kennenlernen <span>→</span></a></div></section>
<section class="section section--paper"><div class="section-head"><div><p class="eyebrow">Wissenswertes. Persönlich. Geprüft.</p><h2>Aktuelles aus Thailand</h2></div><a class="text-link" href="news.php">Alle Beiträge →</a></div><div class="news-grid" data-reveal><a class="news-card" href="news.php"><img src="assets/img/news-card-1.jpg" alt="Bangkok – Nachrichten und Hintergründe" loading="lazy"><div><time>THAILAND AKTUELL</time><h3>Einordnungen statt schneller Schlagzeilen</h3><p>Was Reisende und Residenten wirklich wissen müssen.</p></div></a><a class="news-card" href="klima.php"><img src="assets/img/news-card-3.jpg" alt="Wetter und Reisezeit in Thailand" loading="lazy"><div><time>REISEWISSEN</time><h3>Wetter, Saison und regionale Unterschiede</h3></div></a><a class="news-card" href="reisevorbereitungen.php"><img src="assets/img/topic-airport.jpg" alt="Ankunft und Reisevorbereitung" loading="lazy"><div><time>GUT VORBEREITET</time><h3>Was vor der Abreise wichtig wird</h3></div></a></div></section>
<section class="story-split" data-reveal><div><p class="eyebrow">Ein gemeinsamer Weg</p><h2>Unsere Geschichte</h2><p>Zwei Kulturen, mehr als zwei Jahrzehnte Thailand-Erfahrung und ein Zuhause, das über Jahre gewachsen ist. ThailandInsight erzählt nicht von außen – sondern aus einem gelebten Alltag.</p><a class="text-link" href="ueber-uns.php">Die ganze Geschichte <span>→</span></a></div><figure><img src="assets/img/ebook-hero-city.jpg" alt="Thailand zwischen Tradition und modernem Leben" loading="lazy"></figure></section>
<?php require __DIR__.'/includes/page-end.php';?>
