<?php
declare(strict_types=1);
require __DIR__.'/auth.php'; admin_require();
require_once __DIR__.'/../includes/cms.php';
function mh(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
$dir=realpath(__DIR__.'/../uploads');$msg='';$err='';
function referenced_media(mixed $value,array &$found):void{if(is_array($value)){foreach($value as $v)referenced_media($v,$found);return;}if(is_string($value)&&str_starts_with($value,'uploads/'))$found[$value]=true;}
$used=[];referenced_media(cms_load(),$used);
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_check((string)($_POST['csrf']??'')))$err='Sicherheitsprüfung fehlgeschlagen.';
 else{$name=basename((string)($_POST['delete']??''));$target=$dir?$dir.DIRECTORY_SEPARATOR.$name:'';$relative='uploads/'.$name;if($name===''||!$dir||!is_file($target))$err='Datei wurde nicht gefunden.';elseif(isset($used[$relative]))$err='Diese Datei wird noch auf einer Seite verwendet und kann nicht gelöscht werden.';elseif(unlink($target))$msg='Nicht verwendete Datei wurde gelöscht.';else$err='Datei konnte nicht gelöscht werden.';}
}
$files=[];if($dir){foreach(scandir($dir)?:[] as $name){if($name==='.'||$name==='..'||$name==='.htaccess')continue;$path=$dir.'/'.$name;if(is_file($path))$files[]=['name'=>$name,'relative'=>'uploads/'.$name,'size'=>filesize($path)?:0,'used'=>isset($used['uploads/'.$name])];}}
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Medienübersicht</title><link rel="stylesheet" href="admin.css?v=2"></head><body><main class="admin-main" style="margin:auto"><p><a href="index.php">← Zur Inhaltsverwaltung</a></p><header><div><p class="kicker">MEDIEN</p><h1>Medienübersicht</h1><p>Hochgeladene Bilder und PDFs. Verwendete Dateien sind vor dem Löschen geschützt.</p></div><span class="design-lock">🔒 Grunddesign geschützt</span></header><?php if($msg):?><div class="notice success"><?=mh($msg)?></div><?php endif;?><?php if($err):?><div class="notice error"><?=mh($err)?></div><?php endif;?><div class="media-grid"><?php foreach($files as $f):?><article class="media-card"><?php if(preg_match('/\.(jpe?g|png|webp|gif)$/i',$f['name'])):?><img src="../<?=mh($f['relative'])?>" alt=""><?php else:?><div style="height:130px;display:grid;place-items:center;font-size:48px">PDF</div><?php endif;?><p><?=mh($f['name'])?><br><?=number_format($f['size']/1024,1,',','.')?> KB</p><?php if($f['used']):?><strong style="color:#9edbbd">Wird verwendet</strong><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=mh(csrf())?>"><button class="danger small" name="delete" value="<?=mh($f['name'])?>" onclick="return confirm('Datei wirklich löschen?')">Löschen</button></form><?php endif;?></article><?php endforeach;?></div></main></body></html>
